<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
</head>
<body>
<div class="content">
    <form action="/save" method="POST">
        <label>Name: </label>
        <input name="name" type="text" size="25" />

        <label>Email: </label>
        <input name="email" type="text" size="25" />
        <input type="hidden" name="token" value="<?php echo $token; ?>" />
        <input name="mySubmit" type="submit" value="Submit!" />
    </form>
</div>
</body>
</html>